# SEO

title: Duong / three.js sketches
tagline: Duong's three.js sketches
description: Duong's 3D work, powered by three.js
author: Nguyen Hoang Duong
social:
  name: Nguyen Hoang Duong
  links:
    - https://github.com/you-create
    - https://www.instagram.com/thechonkypenguin
    - https://unsplash.com/@you_create
    - https://dribbble.com/you_create
    - https://medium.com/@you_create

plugins:
  - jekyll-seo-tag

# Pages

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /sketch/:title

# Dev

exclude: [bundle,node_modules]
disable_disk_cache: true
